binary_sensor:

  - platform: template
    sensors:


############################################################################
#                                                                          #
#   HA Update Available                                                    #
#                                                                          #
############################################################################

      ha_update_available:
        friendly_name: "HA Update Available"
        value_template: >-
          {{ not is_state( "sensor.ha_available_version", states("sensor.ha_current_version") ) }}