sensor:

############################################################################
#                                                                          #
#   HA Current Version                                                     #
#                                                                          #
############################################################################

  - platform: version
    name: HA Current Version
    source: local



############################################################################
#                                                                          #
#   HA Available Version                                                   #
#                                                                          #
############################################################################

  - platform: version
    name: HA Available Version
    source: container
    image: default
    beta: false

############################################################################
#                                                                          #
#   HA Update Available                                                    #
#                                                                          #
############################################################################

  # - platform: template
  #   sensors:
  #     ha_update_available:
  #       friendly_name: "HA Update Available"
  #       icon_template: mdi:update
  #       value_template: >-
  #         {% if is_state( "sensor.ha_current_version", states('sensor.ha_available_version') ) %}
  #             no
  #         {% else %}
  #             yes
  #         {% endif %}



############################################################################
#                                                                          #
#   HA DB Information                                                      #
#                                                                          #
############################################################################

#   - platform: sql
#     db_url: !secret synology_db_connection
#     queries:
#       - name: DB size
#         query: 'SELECT table_schema "homeassistant", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
#         column: 'value'
#         unit_of_measurement: MB
#       - name: Events size
#         query: 'SELECT table_schema "homeassistant", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" and table_name="events" GROUP BY table_schema;'
#         column: 'value'
#         unit_of_measurement: MB
#       - name: States size
#         query: 'SELECT table_schema "homeassistant", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" and table_name="states" GROUP BY table_schema;'
#         column: 'value'
#         unit_of_measurement: MB
