#################################################################
#                                                               #
#                    Packages/last ip login                     #
#   https://github.com/custom-components/sensor.authenticated   #
#                                                               #
#                                                               #
#################################################################




#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

sensor:

  # https://github.com/custom-components/sensor.authenticated ##
  - platform: authenticated         


  - platform: template
    sensors:
      authentication_known_ip_info:
        value_template: >-
          {% if is_state('sensor.last_successful_authentication.attributes.new_ip', 'true') %}
            yes
          {% else %}
            no
          {% endif %}