trigger_camera:
  name: Trigger Camera
  description: Triggers a camera
  target:
     entity:
        integration: blueiris
        domain: camera

move_to_preset:
  name: Move to Preset
  description: Moves the selected camera to the specified preset
  target:
     entity:
        integration: blueiris
        domain: camera
  fields:
     preset:
      name: Preset
      description: Desired preset
      required: true
      example: "1"
      default: "1"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "10"
            - "11"
            - "12"
            - "13"
            - "14"
            - "15"
            - "16"
            - "17"
            - "18"
            - "19"
            - "20"
            - "21"
            - "22"
            - "23"
            - "24"
            - "25"
            - "26"
            - "27"
            - "28"
            - "29"
            - "30"
            - "31"
            - "32"
            - "33"
            - "34"
            - "35"
            - "36"
            - "37"
            - "38"
            - "39"
            - "40"
