########################################################
#   צבע אדום                                           #
########################################################
sensor:
  # - platform: rest
  #   resource: https://www.oref.org.il/WarningMessages/alert/alerts.json
  #   value_template: "{{ value_json.data if value_json else [] }}"
  #   headers:
  #     Accept: application/json
  #     Content-Type: application/json
  #     x-requested-with: XMLHttpRequest
  #     Referer: https://www.oref.org.il//12481-he/Pakar.aspx
  #   scan_interval: 2


############################################################################
#                                                                          #
#   Redalert History Count                                                 #
#                                                                          #
############################################################################

  - platform: template
    sensors:
      redalert_history_count:
        friendly_name: "Red Alert History Count"
        value_template: >-
          {% set count = namespace(value=0) %}
          {% for alarm in state_attr('sensor.redalert_history', 'history') %}
            {% set count.value = count.value + 1 %}
          {% endfor %}
          {{ count.value }}



############################################################################
#                                                                          #
#   Redalert Current                                                       #
#                                                                          #
############################################################################

  - platform: rest
    resource: http://192.168.1.107:49000/current
    name: redalert
    value_template: 'OK'
    json_attributes:
      - alert
      - current
    scan_interval: 5
    timeout: 30



############################################################################
#                                                                          #
#   Redalert History                                                       #
#                                                                          #
############################################################################

  - platform: rest
    resource: http://192.168.1.107:49000/history
    name: redalert_history
    value_template: 'OK'
    json_attributes:
      - "history"
    scan_interval: 120
    timeout: 30

logger:
  default: warning
  logs:
    homeassistant.helpers.template: error
  

binary_sensor:
  - platform: template
    sensors:
      home_alert:
        friendly_name: "Missle Alert Home"  
        value_template: "{{ 'באר שבע' in states('sensor.rest_sensor') }}"


############################################################################
#                                                                          #
#   Redalert All                                                           #
#                                                                          #
############################################################################

      redalert_all:
        friendly_name: "Redalert All"
        value_template: >-
          {{ state_attr('sensor.redalert', 'alert') == true }}


############################################################################
#                                                                          #
#   Redalert Ashdod                                                        #
#                                                                          #
############################################################################

      redalert_ashdod:
        friendly_name: "Redalert Ashdod"
        value_template: >-
          {{ state_attr('sensor.redalert', 'alert') == true and 
                    'אשדוד - יא,יב,טו,יז,מרינה' in state_attr('sensor.redalert', 'current')['data'] }}

############################################################################
#                                                                          #
#   Redalert Beer Sheva                                                    #
#                                                                          #
############################################################################
 
      redalert_beer_sheva:
        friendly_name: "Redalert Beer Sheva" 
        value_template: >-
          {{ state_attr('sensor.redalert', 'alert') == true and 
                    'באר שבע' in state_attr('sensor.redalert', 'current')['data'] }}


############################################################################
#                                                                          #
#   Redalert Qiryat Gat                                                    #
#                                                                          #
############################################################################

      redalert_qiryat_gat:
        friendly_name: "Redalert Qiryat Gat"
        value_template: >-
          {{ state_attr('sensor.redalert', 'alert') == true and 
                    'קריית גת, כרמי גת' in state_attr('sensor.redalert', 'current')['data'] }}

# automation:
#   - alias: Alarm in Beer Sheva
#     description: When Sound Alarm Sonos & Yeeligh Activated
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.home_alert
#         from: 'off'
#         to: 'on'
#     condition: []
#     action:
#       - service: script.sonos_say_in_hebrew
#         data:
#           sonos_entity: media_player.sonos_living_room
#           volume: 0.9
#           message: אַזְעָקָה . יֶרִי טִילִים עַל בְּאֵר-שֶׁבַע . רוּץ לַמֶּרְחָב הַמּוּגָן
#           delay: '00:00:05' 

#       - service: media_player.volume_set
#         data:
#           entity_id: media_player.avi_echo_dot
#           volume_level: '1'  
#       - data:
#           data:
#             type: tts
#           message: Missile Attack, Get out from bed and go to a Safe Area
#           target:
#           - media_player.avi_echo_dot
#         service: notify.alexa_media  


#       - service: scene.create
#         data:
#           scene_id: before
#           snapshot_entities:
#             - light.gateway_light_34ce008d4e2e
#             - light.kitchen_strip_lamp
#             - light.computer_room

#       - service: light.turn_on
#         target:
#           entity_id:
#           - light.gateway_light_34ce008d4e2e
#           - light.kitchen_strip_lamp
#           - light.computer_room
#         data:
#           effect: Alarm
#           color_name: red

#       - delay:
#           hours: 0
#           minutes: 0
#           seconds: 30
#           milliseconds: 0

#       - service: scene.turn_on
#         data: {}
#         target:
#           entity_id: scene.before


#       - data:
#           message: שים לב, התראת צבע אדום
#         service: notify.avi_telegram
#       - data:
#           message: שימי לב, התראת צבע אדום
#         service: notify.nurit_telegram



  # - alias: off Missle Alert light after 2 minutes
  #   description: ''
  #   trigger:
  #     entity_id:
  #     - light.gateway_light_34ce008d4e2e
  #     - light.kitchen_strip_lamp
  #     - light.computer_room
  #     from: 'off'
  #     platform: state
  #     to: 'on'
  #   condition: []
  #   action:
  #   - delay: 00:02:00
  #   - data:
  #       entity_id:
  #       - light.gateway_light_34ce008d4e2e
  #       - light.kitchen_strip_lamp
  #       - light.computer_room
  #     service: light.turn_off  
      

  # - alias: Alert Missle alert At Home
  #   trigger:
  #       - platform: state
  #         entity_id:
  #         - binary_sensor.home_alert
  #         from: "off"
  #         to: "on"  
  #   condition: []
  #   action:
  #   - service: media_player.volume_set
  #     data:
  #       entity_id: media_player.echo_show
  #       volume_level: '1'  
  #   - data:
  #       data:
  #         type: tts
  #       message: Missile Attack! Go to a Safe Area!, I repeat, Missile Attack!
  #       target:
  #       - media_player.echo_show
  #     service: notify.alexa_media     

  #   - service: scene.create
  #     data:
  #       scene_id: before
  #       snapshot_entities:
  #       - light.gateway_light_34ce008d4e2e
  #       - light.kitchen_strip_lamp
  #       - light.computer_room
  #   - service: light.turn_on
  #     target:
  #       entity_id:
  #       - light.gateway_light_34ce008d4e2e
  #       - light.kitchen_strip_lamp
  #       - light.computer_room
  #     data:
  #       effect: Alarm
  #       color_name: red

  #   - service: media_player.volume_set
  #     data:
  #       entity_id: media_player.avi_echo_dot
  #       volume_level: '1'  
  #   - data:
  #       data:
  #         type: tts
  #       message: Missile Attack, Get out from bed and go to a Safe Area
  #       target:
  #       - media_player.avi_echo_dot
  #     service: notify.alexa_media 

  #   - data:
  #       message: שים לב, התראת צבע אדום
  #     service: notify.avi_telegram
  #   - data:
  #       message: שימי לב, התראת צבע אדום
  #     service: notify.nurit_telegram
  