###############################################
#   life360                                   #
###############################################
life360:
  accounts:
    - username: !secret username
      password: !secret password
  driving_speed: 29
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3

    
###############################################
#   Sensors                                   #
############################################### 
sensor:
  - platform: template
    sensors:
      life360_avi_battery:
        friendly_name: "Avi battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_avi_abeksis.attributes.battery }}

      life360_nurit_battery:
        friendly_name: "Nurit battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_nurit.attributes.battery }}
          
      life360_yakir_battery:
        friendly_name: "Yakir battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_yakir.attributes.battery }}

      life360_liran_battery:
        friendly_name: "Liran battery"
        icon_template: mdi:battery
        unit_of_measurement: '%'
        value_template: >-
          {{ states.device_tracker.life360_liran.attributes.battery }}          